#!/bin/bash

if [[ "$(basename $(pwd))" != "build" ]]; then
  echo "please run from build directory"
  exit 1
fi

if [[ ! -e "Makefile" ]]; then
  echo "Makefile not found; have you run cmake yet?"
  echo "please consider running local.do_cmake.sh"
  exit 1
fi

CONF_PATH=${HOME}/.ceph_ccache/ceph_ccache.conf
RELEASE_NAME=$(basename $(dirname $(pwd)) | cut -f2 -d'.')

source ${CONF_PATH}
source ${CEPH_CCACHE_EPOCHS_EXPORTS_FN}

export CCACHE_DIR
export CCACHE_BASEDIR

echo "using BUILD_DATE=${BUILD_DATE}, SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}"
make "$@"
