#!/bin/bash
#
# Make wrapper to build ceph using our scripts 
# Copyright (C) 2019  Joao Eduardo Luis <joao@wipwd.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

if [[ "$(basename $(pwd))" != "build" ]]; then
  echo "please run from build directory"
  exit 1
fi

if [[ ! -e "Makefile" ]]; then
  echo "Makefile not found; have you run cmake yet?"
  echo "please consider running local.do_cmake.sh"
  exit 1
fi

CONF_PATH=${HOME}/.ceph_ccache/ceph_ccache.conf
RELEASE_NAME=$(basename $(dirname $(pwd)) | cut -f2 -d'.')

source ${CONF_PATH}
source ${CEPH_CCACHE_EPOCHS_EXPORTS_FN}

export CCACHE_DIR
export CCACHE_BASEDIR

echo "using BUILD_DATE=${BUILD_DATE}, SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}"
make "$@"
