#!/bin/bash

real_path=$(realpath $0)
srcdir=$(dirname ${real_path})

usage() {
  cat << EOF
usage: $0 <start|stop> <who>

EOF
}

is_userpass() {
  who="${1}"
  [[ -z "${who}" ]] && exit 1

  if ! pass ls openvpn/${who}/is_userpass >&/dev/null; then
    return 1
  fi
  return 0
}

is_passphrase() {
  who="${1}"
  [[ -z "${who}" ]] && exit 1
  if ! pass ls openvpn/${who}/is_passphrase >&/dev/null; then
    return 1
  fi
  return 0
}

is_true() {
  if [[ $1 -eq 0 ]]; then return 0 ; else return 1 ; fi
}

openvpn_start() {
  [[ $# -lt 1 ]] && usage && exit 1
  who="${1}"

  if ! which expect 2>/dev/null ; then
    echo "unable to find 'expect'; please install package on your system"
    exit 1
  fi

  is_userpass "${who}"
  use_userpass=$?
  is_passphrase "${who}"
  use_passphrase=$?

  if is_true $use_userpass && is_true $use_passphrase; then
#  [[ $use_userpass && $use_passphrase ]] && \
    >&2 echo "error: '${who}' specified as both userpass and passphrase" && \
    exit 1
  fi

  if ! is_true $use_userpass && ! is_true $use_passphrase ; then
    >&2 echo "error: '${who}' does not specify userpass or passphrase" && \
    exit 1
  fi

  method=
  if is_true $use_userpass ; then
    method="userpass"
  else
    method="passphrase"
  fi

  ${srcdir}/lib/ovpn-do-connect ${who} ${method}
}

if [[ $# -lt 2 ]]; then
  usage
  exit 1
fi

action=${1}
who=${2}

echo "${action} ${who}"

case ${action} in
  stop)
    sudo systemctl stop openvpn@${who}
    exit $?
    ;;
  start)
    openvpn_start ${who}
    ;;
esac
