#!/usr/bin/expect
#
# Process authentication procedure to connect to a vpn 
# Copyright (C) 2019  Joao Eduardo Luis <joao@wipwd.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

set who [lindex $argv 0];
set method [lindex $argv 1];

set is_userpass false

puts [exec pwd]

if { $method == "userpass" } {
  set is_userpass true
}

set username ""
set password ""
set passphrase ""

if { $is_userpass } {
  if { [catch {set username [exec pass show openvpn/$who/username]} msg] } {
    puts "expected username for '$who'; abort"
    exit 1
  }
  if {[catch {set password [exec pass show openvpn/$who/password]} msg] } {
    puts "expected password for '$who'; abort"
    exit 1
  }
} else {
  if {[catch {set passphrase [exec pass show openvpn/$who/passphrase]} msg]} {
    puts "expected passphrase for '$who': $msg ; abort"
    exit 1
  }
}

#puts "user: $username, pw: $password, passphrase: $passphrase"

spawn /usr/bin/sudo systemctl start openvpn@$who

expect {
  "*sudo*password*" {
    stty -echo
    interact -u tty_spawn_id -o "\r" return
    stty echo
    exp_continue
  }

  "*Private Key*" {
    send -- "$passphrase\r"
    exp_continue
  }
  "*Username*" {
    send -- "$username\r"
    expect "*Password*" {
      send -- "$password\r"
    }
    interact
  }
  eof
}

exit 0
